branches:
  only:
  - main

dist: trusty
sudo: true

language: node_js
node_js:
  - '12.0'

services:
  - docker

addons:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - cd covid-modelizer-app/src

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_success:

  - docker-compose build
  - docker tag $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:latest
